# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cecília Assis
email: cyassis@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Cecília Assis' personal website + blog that ensembles everything that is meanfingful to her.
  Focuses on Machine Learning, Ruby, Python and Finances.
# twitter_username: username
keywords: machine learning, ruby, python
github_username: ceciliassis
minimal_mistakes_skin: default
search: true
repository: ceciliassis/ceciliassis.github.io
url: https://ceciliassis.com

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.19.1
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Cecília Assis"
  avatar : "/assets/images/bio-photo.png"
  bio    : "I love coding, it's my life and my main goal is to do it the best way possible! Join me on my quest!"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://ceciliassis.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ceciliassis"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/ceciliassis"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/aceciliassis"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ceciliassis"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/ceciliassis"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/aceciliassis"



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      
comments:
  provider: "disqus"
  disqus:
    shortname: "ceciliassis"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: 'google-gtag'
  google:
    tracking_id: 'G-1P0HRYT5ZL'
    anonymize_ip: false # default

# google:
#   search_engine_id: YOUR_SEARCH_ENGINE_ID

google_site_verification: JrcXAfsGUSKkfvwADPJ8fPUgIQ_FEeq-HOKRAoaQERo
